# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = ENV['HOME']+"/.vagrant.d/playbook.yml"
      ansible.sudo = true
  end

end
